language: c

sudo:
  - required

os:
  - linux

compiler:
  - gcc

branches:
  only:
    - master

before_install:
  - sudo apt install libcunit1 libcunit1-dev

install:
  - cd test
  - cmake .
  - make
  - cd ../

script:
  - ./ci.sh
  - ./get_code_cov.bash

after_success:
  - bash <(curl -s https://codecov.io/bash)
